services:
  # ------------------- Zookeeper ---------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - automatch-network

  # ---------------------- Kafka --------------------------
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - automatch-network

  # ------------------- Kafka UI --------------------------
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "automatch-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
    networks:
      - automatch-network

  # ------------------- PostgreSQL (Payments) ----------------------------
  postgres_payments:
    image: postgres:16
    container_name: postgres_payments
    restart: always
    environment:
      POSTGRES_DB: automatch_payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_payments:/var/lib/postgresql/data
    networks:
      - automatch-network

  # ------------------- PostgreSQL (Notifications) ----------------------------
  postgres_notifications:
    image: postgres:16
    container_name: postgres_notifications
    restart: always
    environment:
      POSTGRES_DB: notifications_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - postgres_data_notifications:/var/lib/postgresql/data
    networks:
      - automatch-network

  # ------------------- PostgreSQL (Messaging) ----------------------------
  postgres_messaging:
    image: postgres:16
    container_name: postgres_messaging
    restart: always
    environment:
      POSTGRES_DB: automatch_messaging
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_messaging:/var/lib/postgresql/data
    networks:
      - automatch-network

  # ------------------ Eureka Server --------------------------
  eureka-server:
    build: ./eureka-server/eureka-server
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - automatch-network

  #----------------- Payments Microservice -------------------------
  payments:
    build: ./payments
    container_name: automatch-payments
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres_payments
      - kafka
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - automatch-network

  #----------------- Notifications Microservice -------------------------
  notifications-service:
    build: ./notifications-service
    container_name: notifications-service
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - postgres_notifications
      - kafka
      - eureka-server
    environment:
      SPRING_APPLICATION_NAME: notifications-service
      SERVER_PORT: 8083
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_notifications:5432/notifications_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    networks:
      - automatch-network

  #----------------- Messaging Microservice -------------------------
  messaging-service:
    build: ./messaging-service
    container_name: messaging-service
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - postgres_messaging
      - kafka
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_NAME: messaging-service
      SERVER_PORT: 8084
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_messaging:5432/automatch_messaging
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    networks:
      - automatch-network

# ---------------------- Vol√∫menes ------------------------------
volumes:
  postgres_data_payments:
  postgres_data_notifications:
  postgres_data_messaging:

# ------------------------ Red ------------------------------------
networks:
  automatch-network:
    external: true