services:
  # ------------------- Zookeeper ---------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - automatch-network

  # ---------------------- Kafka --------------------------
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # SOLO LISTENER INTERNO PARA DOCKER
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - automatch-network

  # ------------------- Kafka UI --------------------------
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    depends_on:
      -
      - kafka
    ports:
      - "8087:8087"
    environment:
      KAFKA_CLUSTERS_0_NAME: "automatch-cluster"

      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
    networks:
      - automatch-network

  # ------------------- PostgreSQL (Payments) ----------------------------
  postgres_payments:
    image: postgres:16
    container_name: postgres_payments
    restart: always
    environment:
      POSTGRES_DB: automatch_payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_payments:/var/lib/postgresql/data
    networks:
      - automatch-network

  # ------------------- PostgreSQL (Notifications) ----------------------------
  postgres_notifications:
    image: postgres:16
    container_name: postgres_notifications
    restart: always
    environment:
      POSTGRES_DB: notifications_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - postgres_data_notifications:/var/lib/postgresql/data
    networks:
      - automatch-network

  # ------------------- PostgreSQL (Messaging) ----------------------------
  postgres_messaging:
    image: postgres:16
    container_name: postgres_messaging
    restart: always
    environment:
      POSTGRES_DB: automatch_messaging
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_messaging:/var/lib/postgresql/data
    networks:
      - automatch-network

  # ------------------- PostgreSQL (Interactions) ----------------------------
  postgres_interactions:
    image: postgres:16
    container_name: postgres_interactions
    restart: always
    environment:
      POSTGRES_DB: automatch_interactions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_data_interactions:/var/lib/postgresql/data
    networks:
      - automatch-network

    # ------------------- PostgreSQL (Inspections) ----------------------------
  postgres-inspections:
    image: postgres:16
    container_name: postgres-inspections
    restart: always
    environment:
      POSTGRES_DB: automatch_inspections
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres_data_inspections:/var/lib/postgresql/data
    networks:
      - automatch-network

  postgres_promos:
    image: postgres:16
    container_name: postgres_promos
    restart: always
    environment:
      POSTGRES_DB: automatch_promos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5439:5432"
    volumes:
      - postgres_data_promos:/var/lib/postgresql/data
    networks:
      - automatch-network

  postgres_iam:
    image: postgres:16
    container_name: postgres_iam
    restart: always
    environment:
      POSTGRES_DB: automatch_iam
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5440:5432"
    volumes:
      - postgres_data_iam:/var/lib/postgresql/data
    networks:
      - automatch-network

  postgres_vehicle:
    image: postgres:16
    container_name: postgres_vehicle
    restart: always
    environment:
      POSTGRES_DB: automatch_vehicle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5441:5432"
    volumes:
      - postgres_data_vehicle:/var/lib/postgresql/data
    networks:
      - automatch-network

  # ------------------ Eureka Server --------------------------
  eureka-server:
    build: ./eureka-server/eureka-server
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - automatch-network

  #----------------- Payments Microservice -------------------------
  payments:
    build: ./payments
    container_name: automatch-payments
    restart: always
    ports:
      - "8093:8093"
    depends_on:
      - postgres_payments
      - kafka
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - automatch-network

  #----------------- Notifications Microservice -------------------------
  notifications-service:
    build: ./notifications-service
    container_name: notifications-service
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - postgres_notifications
      - kafka
      - eureka-server
    environment:
      SPRING_APPLICATION_NAME: notifications-service
      SERVER_PORT: 8083
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_notifications:5432/notifications_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - automatch-network

  #----------------- Messaging Microservice -------------------------
  messaging-service:
    build: ./messaging-service
    container_name: messaging-service
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - postgres_messaging
      - kafka
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_NAME: messaging-service
      SERVER_PORT: 8084
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_messaging:5432/automatch_messaging
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

      SERVICES_NOTIFICATIONS_URL: http://notifications-service:8083
    networks:
      - automatch-network

  # ------------------- Interactions Microservice ----------------------------
  interactions-service:
    build: ./interactions-service
    container_name: interactions-service
    restart: always
    depends_on:
      - postgres_interactions
      - kafka
      - eureka-server
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_NAME: interactions-service
      SERVER_PORT: 8085
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_interactions:5432/automatch_interactions
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    networks:
      - automatch-network

  # ------------------- Inspections Microservice ----------------------------
  inspections-service:
    build: ./inspections-service
    container_name: automatch-inspections
    restart: always
    depends_on:
      - postgres-inspections
      - kafka
      - eureka-server
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_NAME: inspections-service
      SERVER_PORT: 8090
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-inspections:5432/automatch_inspections
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_CLIENT_ENABLED: "true"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    networks:
      - automatch-network

    # ------------------- Promotions & Announcements Microservice ----------------------------
  promotions-announcement-service:
    build: ./promotions-announcement-service
    container_name: automatch-promotions
    restart: always
    depends_on:
      - postgres_promos
      - kafka
      - eureka-server
    ports:
      - "8091:8091"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_NAME: promotions-announcement-service
      SERVER_PORT: 8091
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_promos:5432/automatch_promos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      AUTOMATCH_TOPIC_CONSUMER: automatch.interaction.created
      AUTOMATCH_TOPIC_PRODUCER: automatch.promotions.published
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

    networks:
      - automatch-network

  api-gateway:
    build: ./ApiGateway-main
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    networks:
      - automatch-network

  iam-service:
    build: ./IAM-service
    container_name: automatch-iam
    restart: always
    depends_on:
      - postgres_iam
      - eureka-server
    ports:
      - "8094:8094"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      SPRING_APPLICATION_NAME: iam-service
      SERVER_PORT: 8094

      POSTGRES_IAM_HOST: postgres_iam
      POSTGRES_IAM_PORT: 5432
      POSTGRES_IAM_DB: automatch_iam
      POSTGRES_IAM_USERNAME: postgres
      POSTGRES_IAM_PASSWORD: postgres

      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

      IAM_JWT_SECRET: iam12345secret

    networks:
      - automatch-network


  # ------------------- PROFILES SERVICE (8095) -------------------
  perfiles-service:
    build: ./Perfiles-Service
    container_name: perfiles-service
    restart: always
    depends_on:
      - eureka-server
    ports:
      - "8095:8095"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_NAME: perfiles-service
      SERVER_PORT: 8095

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

    networks:
      - automatch-network

  vehicle-service:
    build: ./Vehicle-Service
    container_name: automatch-vehicle
    restart: always
    depends_on:
      - postgres_vehicle
      - kafka
      - eureka-server
    ports:
      - "8096:8096"
    environment:
      SPRING_PROFILES_ACTIVE: docker

      SPRING_APPLICATION_NAME: vehicle-service
      SERVER_PORT: 8096

      PG_HOST: postgres_vehicle
      PG_PORT: 5432
      PG_DB: automatch_vehicle
      PG_USER: postgres
      PG_PASSWORD: postgres

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_vehicle:5432/automatch_vehicle
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

      AUTHORIZATION_JWT_SECRET: WriteHereYourSecretStringForTokenSigningCredentials
      AUTHORIZATION_JWT_EXPIRATION_DAYS: 7

    networks:
      - automatch-network

# ---------------------- Vol√∫menes ------------------------------
volumes:
  postgres_data_payments:
  postgres_data_notifications:
  postgres_data_messaging:
  postgres_data_interactions:
  postgres_data_inspections:
  postgres_data_promos:
  postgres_data_iam:
  postgres_data_vehicle:

# ------------------------ Red ------------------------------------
networks:
  automatch-network:
    driver: bridge
